<a href="https://colab.research.google.com/github/Zobiya-12/AIML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementing Basic Data Structures using Numpy.

In [ ]:
#Implementing Lists using Numpy
import numpy as np
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Implementing Arrays using Numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#Identifying type usinf "type()" method
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#Performing mathematical operations
#1.Multiplication
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
mul = np.multiply(a, b)
print(mul)
#2.division
div = np.divide(a, b)
print(div)
#3.Poweroff
power = np.power(a, b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
#Combine text with Numpy fucntion to generate a textual output
import numpy as np
text1 = np.array(["Addition of Two: "] , dtype = str)
text2 = np.array(["array1 + array2"], dtype = str)
fulltext = np.char.add(text1, text2)#gives element wise concatenation.
print(fulltext)

['Addition of Two: array1 + array2']


In [ ]:
#Implement np.sin(), log(), np.exp(), log2()
import numpy as np
a = np.array([1,2,3])
sin = np.sin(a)
print(sin)
log = np.log(a)
print(log)
exp = np.exp(a)
print(exp)
log2 = np.log2(a)
print(log2)

[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.        1.        1.5849625]
